name: "Bug Report"
description: "Report Zyxel Nebula OpenAPI bug"
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details to help us address the issue:
  - type: textarea
    id: "title"
    attributes:
      label: "Brief Title"
      description: "Provide a short summary of the issue"
      placeholder: "Enter a brief title..."
      required: true
  - type: textarea
    id: "steps-to-reproduce"
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps that can help us recreate the issue"
      required: true
  - type: textarea
    id: "expected-behavior"
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen"
      required: true
  - type: textarea
    id: "actual-behavior"
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happened"
      required: true
  - type: textarea
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: "Add any other context or information about the issue"
      required: false
